"""Identifier helpers. IDs are generated by the system, never accepted from the LLM as-is."""

from __future__ import annotations

import re
import secrets
import uuid

_UUID_RE = re.compile(r"^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$")


def new_id() -> str:
    return str(uuid.uuid4())


def new_nonce() -> str:
    return secrets.token_hex(16)


def is_uuid(value: object) -> bool:
    return isinstance(value, str) and bool(_UUID_RE.match(value))
